import { GitHubOperation } from "@/generated/prisma"

type GitHubOp = keyof typeof GitHubOperation

export const OPERATION_LABELS: Record<GitHubOp, string> = {
  // Repository
  REPOSITORY_CREATE: "Create Repository",
  REPOSITORY_GET: "Get Repository",
  REPOSITORY_LIST: "List Repositories",
  REPOSITORY_UPDATE: "Update Repository",
  REPOSITORY_DELETE: "Delete Repository",
  REPOSITORY_FORK: "Fork Repository",
  REPOSITORY_LIST_CONTRIBUTORS: "List Contributors",
  REPOSITORY_LIST_LANGUAGES: "List Languages",
  REPOSITORY_TRANSFER: "Transfer Repository",
  REPOSITORY_DISPATCH: "Repository Dispatch",
  REPOSITORY_CHECK_COLLABORATOR: "Check Collaborator",
  REPOSITORY_LIST_EVENTS: "List Events",
  // Issues
  ISSUE_CREATE: "Create Issue",
  ISSUE_GET: "Get Issue",
  ISSUE_UPDATE: "Update Issue",
  ISSUE_CLOSE: "Close Issue",
  ISSUE_REOPEN: "Reopen Issue",
  ISSUE_LIST: "List Issues",
  ISSUE_ADD_LABELS: "Add Labels",
  ISSUE_REMOVE_LABEL: "Remove Label",
  ISSUE_CREATE_COMMENT: "Create Comment",
  ISSUE_LIST_COMMENTS: "List Comments",
  ISSUE_UPDATE_COMMENT: "Update Comment",
  ISSUE_DELETE_COMMENT: "Delete Comment",
  ISSUE_ASSIGN: "Assign Issue",
  ISSUE_UNASSIGN: "Unassign Issue",
  // Pull Requests
  PULL_REQUEST_CREATE: "Create PR",
  PULL_REQUEST_GET: "Get PR",
  PULL_REQUEST_LIST: "List PRs",
  PULL_REQUEST_UPDATE: "Update PR",
  PULL_REQUEST_MERGE: "Merge PR",
  PULL_REQUEST_CLOSE: "Close PR",
  PULL_REQUEST_REOPEN: "Reopen PR",
  PULL_REQUEST_LIST_REVIEWS: "List Reviews",
  PULL_REQUEST_CREATE_REVIEW: "Create Review",
  PULL_REQUEST_REQUEST_REVIEWERS: "Request Reviewers",
  PULL_REQUEST_LIST_COMMITS: "List Commits",
  PULL_REQUEST_LIST_FILES: "List Files",
  PULL_REQUEST_CREATE_REVIEW_COMMENT: "Review Comment",
  // Files
  FILE_GET: "Get File",
  FILE_CREATE: "Create File",
  FILE_UPDATE: "Update File",
  FILE_DELETE: "Delete File",
  FILE_LIST: "List Files",
  FILE_GET_CONTENTS: "Get Contents",
  FILE_CREATE_OR_UPDATE: "Create or Update File",
  // Branches
  BRANCH_LIST: "List Branches",
  BRANCH_GET: "Get Branch",
  BRANCH_CREATE: "Create Branch",
  BRANCH_DELETE: "Delete Branch",
  BRANCH_RENAME: "Rename Branch",
  BRANCH_SET_PROTECTION: "Set Protection",
  // Releases
  RELEASE_CREATE: "Create Release",
  RELEASE_GET: "Get Release",
  RELEASE_LIST: "List Releases",
  RELEASE_UPDATE: "Update Release",
  RELEASE_DELETE: "Delete Release",
  RELEASE_UPLOAD_ASSET: "Upload Asset",
  // Workflows
  WORKFLOW_LIST: "List Workflows",
  WORKFLOW_GET: "Get Workflow",
  WORKFLOW_DISPATCH: "Dispatch Workflow",
  WORKFLOW_RUN_LIST: "List Runs",
  WORKFLOW_RUN_GET: "Get Run",
  WORKFLOW_RUN_CANCEL: "Cancel Run",
  WORKFLOW_RUN_RE_RUN: "Re-run",
  WORKFLOW_RUN_LIST_JOBS: "List Jobs",
  // Gists
  GIST_CREATE: "Create Gist",
  GIST_GET: "Get Gist",
  GIST_LIST: "List Gists",
  GIST_UPDATE: "Update Gist",
  GIST_DELETE: "Delete Gist",
  GIST_STAR: "Star Gist",
  // Search
  SEARCH_REPOSITORIES: "Search Repos",
  SEARCH_ISSUES: "Search Issues",
  SEARCH_PULL_REQUESTS: "Search PRs",
  SEARCH_CODE: "Search Code",
  SEARCH_USERS: "Search Users",
  SEARCH_COMMITS: "Search Commits",
  SEARCH_TOPICS: "Search Topics",
  // Users
  USER_GET: "Get User",
  USER_GET_CURRENT: "Get Current User",
  USER_LIST_REPOS: "User Repos",
  USER_LIST_FOLLOWERS: "List Followers",
  USER_LIST_FOLLOWING: "List Following",
  // Organizations
  ORG_GET: "Get Org",
  ORG_LIST: "List Orgs",
  ORG_LIST_MEMBERS: "List Members",
  ORG_LIST_TEAMS: "List Teams",
  ORG_LIST_REPOS: "Org Repos",
  ORG_CREATE_REPO: "Create Org Repo",
  ORG_INVITE_MEMBER: "Invite Member",
  ORG_REMOVE_MEMBER: "Remove Member",
  // Discussions
  DISCUSSION_CREATE: "Create Discussion",
  DISCUSSION_GET: "Get Discussion",
  DISCUSSION_LIST: "List Discussions",
  DISCUSSION_UPDATE: "Update Discussion",
  DISCUSSION_DELETE: "Delete Discussion",
  // Codespaces
  CODESPACES_LIST: "List Codespaces",
  CODESPACES_GET: "Get Codespace",
  CODESPACES_CREATE: "Create Codespace",
  CODESPACES_START: "Start Codespace",
  CODESPACES_STOP: "Stop Codespace",
  CODESPACES_DELETE: "Delete Codespace",
  CODESPACES_UPDATE: "Update Codespace",
  CODESPACES_EXPORT: "Export Codespace",
  CODESPACES_LIST_FOR_REPO: "Repo Codespaces",
  CODESPACES_LIST_MACHINE_TYPES: "Machine Types",
  CODESPACES_LIST_SECRETS: "List Secrets",
  CODESPACES_CREATE_SECRET: "Create Secret",
  // Copilot
  COPILOT_LIST_SEATS: "List Seats",
  COPILOT_ADD_SEAT: "Add Seat",
  COPILOT_REMOVE_SEAT: "Remove Seat",
  COPILOT_GET_SETTINGS: "Get Settings",
  COPILOT_UPDATE_SETTINGS: "Update Settings",
  COPILOT_LIST_SPACES: "List Spaces",
  COPILOT_GET_SPACE: "Get Space",
  COPILOT_CREATE_SPACE: "Create Space",
  COPILOT_UPDATE_SPACE: "Update Space",
  COPILOT_DELETE_SPACE: "Delete Space",
  COPILOT_LIST_SPACE_RESOURCES: "Space Resources",
  COPILOT_ADD_SPACE_RESOURCE: "Add Resource",
  COPILOT_REMOVE_SPACE_RESOURCE: "Remove Resource",
  COPILOT_GET_AGENT_POLICY: "Get Policy",
  COPILOT_UPDATE_AGENT_POLICY: "Update Policy",
  // Rulesets
  RULESET_LIST: "List Rulesets",
  RULESET_GET: "Get Ruleset",
  RULESET_CREATE: "Create Ruleset",
  RULESET_UPDATE: "Update Ruleset",
  RULESET_DELETE: "Delete Ruleset",
  RULESET_LIST_RULE_EVALUATIONS: "Rule Evaluations",
  RULESET_GET_RULE_SUITE: "Get Rule Suite",
  RULESET_LIST_ORG_RULESETS: "Org Rulesets",
  // Environments
  ENVIRONMENT_LIST: "List Environments",
  ENVIRONMENT_GET: "Get Environment",
  ENVIRONMENT_CREATE: "Create Environment",
  ENVIRONMENT_UPDATE: "Update Environment",
  ENVIRONMENT_DELETE: "Delete Environment",
  ENVIRONMENT_LIST_SECRETS: "Env Secrets",
  ENVIRONMENT_GET_SECRET: "Get Env Secret",
  ENVIRONMENT_CREATE_SECRET: "Create Env Secret",
  ENVIRONMENT_DELETE_SECRET: "Delete Env Secret",
  ENVIRONMENT_LIST_PROTECTION_RULES: "Protection Rules",
  // Secrets
  SECRET_LIST_REPO: "Repo Secrets",
  SECRET_GET_REPO: "Get Repo Secret",
  SECRET_CREATE_REPO: "Create Repo Secret",
  SECRET_DELETE_REPO: "Delete Repo Secret",
  SECRET_LIST_ORG: "Org Secrets",
  SECRET_GET_ORG: "Get Org Secret",
  SECRET_CREATE_ORG: "Create Org Secret",
  SECRET_DELETE_ORG: "Delete Org Secret",
  SECRET_GET_PUBLIC_KEY: "Get Public Key",
  SECRET_GET_ORG_PUBLIC_KEY: "Get Org Public Key",
  SECRET_LIST_SELECTED_REPOS: "Selected Repos",
  SECRET_SET_SELECTED_REPOS: "Set Selected Repos",
  // Deployments
  DEPLOYMENT_LIST: "List Deployments",
  DEPLOYMENT_GET: "Get Deployment",
  DEPLOYMENT_CREATE: "Create Deployment",
  DEPLOYMENT_LIST_STATUSES: "List Statuses",
  DEPLOYMENT_GET_STATUS: "Get Status",
  DEPLOYMENT_CREATE_STATUS: "Create Status",
  DEPLOYMENT_DELETE: "Delete Deployment",
  DEPLOYMENT_SET_STATUS: "Set Status",
  // Packages
  PACKAGE_LIST_FOR_USER: "User Packages",
  PACKAGE_LIST_FOR_ORG: "Org Packages",
  PACKAGE_GET: "Get Package",
  PACKAGE_DELETE: "Delete Package",
  PACKAGE_RESTORE: "Restore Package",
  PACKAGE_LIST_VERSIONS: "List Versions",
  PACKAGE_GET_VERSION: "Get Version",
  PACKAGE_DELETE_VERSION: "Delete Version",
  PACKAGE_RESTORE_VERSION: "Restore Version",
  PACKAGE_LIST_DOCKER_IMAGES: "Docker Images",
  // Attestations
  ATTESTATION_LIST_FOR_REPO: "Repo Attestations",
  ATTESTATION_GET: "Get Attestation",
  ATTESTATION_CREATE: "Create Attestation",
  ATTESTATION_LIST_FOR_ORG: "Org Attestations",
  ATTESTATION_VERIFY: "Verify Attestation",
  // Agent Tasks
  AGENT_TASK_LIST: "List Tasks",
  AGENT_TASK_GET: "Get Task",
  AGENT_TASK_CREATE: "Create Task",
  AGENT_TASK_UPDATE: "Update Task",
  AGENT_TASK_CANCEL: "Cancel Task",
  AGENT_TASK_GET_LOGS: "Get Logs",
  // Artifacts
  ARTIFACT_LIST: "List Artifacts",
  ARTIFACT_GET: "Get Artifact",
  ARTIFACT_DELETE: "Delete Artifact",
  ARTIFACT_DOWNLOAD: "Download Artifact",
  ARTIFACT_UPLOAD: "Upload Artifact",
  ARTIFACT_GET_ARCHIVE_URL: "Get Archive URL",
  // Projects V2
  PROJECT_V2_LIST: "List Projects",
  PROJECT_V2_GET: "Get Project",
  PROJECT_V2_CREATE: "Create Project",
  PROJECT_V2_UPDATE: "Update Project",
  PROJECT_V2_DELETE: "Delete Project",
  PROJECT_V2_LIST_ITEMS: "List Items",
  PROJECT_V2_ADD_ITEM: "Add Item",
  PROJECT_V2_UPDATE_ITEM: "Update Item",
  PROJECT_V2_DELETE_ITEM: "Delete Item",
  PROJECT_V2_LIST_FIELDS: "List Fields",
  PROJECT_V2_CREATE_FIELD: "Create Field",
  PROJECT_V2_UPDATE_FIELD_VALUE: "Update Field Value",
  // Security Advisories
  ADVISORY_LIST: "List Advisories",
  ADVISORY_GET: "Get Advisory",
  ADVISORY_CREATE: "Create Advisory",
  ADVISORY_UPDATE: "Update Advisory",
  ADVISORY_LIST_REPOS_AFFECTED: "Affected Repos",
  ADVISORY_REPORT: "Report Vulnerability",
}

export const OPERATION_GROUPS: { label: string; ops: GitHubOp[] }[] = [
  {
    label: "📦 Repository",
    ops: ["REPOSITORY_CREATE", "REPOSITORY_GET", "REPOSITORY_LIST", "REPOSITORY_UPDATE", "REPOSITORY_DELETE", "REPOSITORY_FORK", "REPOSITORY_LIST_CONTRIBUTORS", "REPOSITORY_LIST_LANGUAGES", "REPOSITORY_TRANSFER", "REPOSITORY_DISPATCH", "REPOSITORY_CHECK_COLLABORATOR", "REPOSITORY_LIST_EVENTS"],
  },
  {
    label: "🐛 Issues",
    ops: ["ISSUE_CREATE", "ISSUE_GET", "ISSUE_UPDATE", "ISSUE_CLOSE", "ISSUE_REOPEN", "ISSUE_LIST", "ISSUE_ADD_LABELS", "ISSUE_REMOVE_LABEL", "ISSUE_CREATE_COMMENT", "ISSUE_LIST_COMMENTS", "ISSUE_UPDATE_COMMENT", "ISSUE_DELETE_COMMENT", "ISSUE_ASSIGN", "ISSUE_UNASSIGN"],
  },
  {
    label: "🔀 Pull Requests",
    ops: ["PULL_REQUEST_CREATE", "PULL_REQUEST_GET", "PULL_REQUEST_LIST", "PULL_REQUEST_UPDATE", "PULL_REQUEST_MERGE", "PULL_REQUEST_CLOSE", "PULL_REQUEST_REOPEN", "PULL_REQUEST_LIST_REVIEWS", "PULL_REQUEST_CREATE_REVIEW", "PULL_REQUEST_REQUEST_REVIEWERS", "PULL_REQUEST_LIST_COMMITS", "PULL_REQUEST_LIST_FILES", "PULL_REQUEST_CREATE_REVIEW_COMMENT"],
  },
  {
    label: "📄 Files",
    ops: ["FILE_GET", "FILE_CREATE", "FILE_UPDATE", "FILE_DELETE", "FILE_LIST", "FILE_GET_CONTENTS", "FILE_CREATE_OR_UPDATE"],
  },
  {
    label: "🌿 Branches",
    ops: ["BRANCH_LIST", "BRANCH_GET", "BRANCH_CREATE", "BRANCH_DELETE", "BRANCH_RENAME", "BRANCH_SET_PROTECTION"],
  },
  {
    label: "🏷️ Releases",
    ops: ["RELEASE_CREATE", "RELEASE_GET", "RELEASE_LIST", "RELEASE_UPDATE", "RELEASE_DELETE", "RELEASE_UPLOAD_ASSET"],
  },
  {
    label: "⚙️ Workflows & CI/CD",
    ops: ["WORKFLOW_LIST", "WORKFLOW_GET", "WORKFLOW_DISPATCH", "WORKFLOW_RUN_LIST", "WORKFLOW_RUN_GET", "WORKFLOW_RUN_CANCEL", "WORKFLOW_RUN_RE_RUN", "WORKFLOW_RUN_LIST_JOBS"],
  },
  {
    label: "📝 Gists",
    ops: ["GIST_CREATE", "GIST_GET", "GIST_LIST", "GIST_UPDATE", "GIST_DELETE", "GIST_STAR"],
  },
  {
    label: "🔍 Search",
    ops: ["SEARCH_REPOSITORIES", "SEARCH_ISSUES", "SEARCH_PULL_REQUESTS", "SEARCH_CODE", "SEARCH_USERS", "SEARCH_COMMITS", "SEARCH_TOPICS"],
  },
  {
    label: "👤 Users",
    ops: ["USER_GET", "USER_GET_CURRENT", "USER_LIST_REPOS", "USER_LIST_FOLLOWERS", "USER_LIST_FOLLOWING"],
  },
  {
    label: "🏢 Organizations",
    ops: ["ORG_GET", "ORG_LIST", "ORG_LIST_MEMBERS", "ORG_LIST_TEAMS", "ORG_LIST_REPOS", "ORG_CREATE_REPO", "ORG_INVITE_MEMBER", "ORG_REMOVE_MEMBER"],
  },
  {
    label: "💬 Discussions",
    ops: ["DISCUSSION_CREATE", "DISCUSSION_GET", "DISCUSSION_LIST", "DISCUSSION_UPDATE", "DISCUSSION_DELETE"],
  },
  {
    label: "☁️ Codespaces",
    ops: ["CODESPACES_LIST", "CODESPACES_GET", "CODESPACES_CREATE", "CODESPACES_START", "CODESPACES_STOP", "CODESPACES_DELETE", "CODESPACES_UPDATE", "CODESPACES_EXPORT", "CODESPACES_LIST_FOR_REPO", "CODESPACES_LIST_MACHINE_TYPES", "CODESPACES_LIST_SECRETS", "CODESPACES_CREATE_SECRET"],
  },
  {
    label: "🤖 Copilot",
    ops: ["COPILOT_LIST_SEATS", "COPILOT_ADD_SEAT", "COPILOT_REMOVE_SEAT", "COPILOT_GET_SETTINGS", "COPILOT_UPDATE_SETTINGS", "COPILOT_LIST_SPACES", "COPILOT_GET_SPACE", "COPILOT_CREATE_SPACE", "COPILOT_UPDATE_SPACE", "COPILOT_DELETE_SPACE", "COPILOT_LIST_SPACE_RESOURCES", "COPILOT_ADD_SPACE_RESOURCE", "COPILOT_REMOVE_SPACE_RESOURCE", "COPILOT_GET_AGENT_POLICY", "COPILOT_UPDATE_AGENT_POLICY"],
  },
  {
    label: "📐 Rulesets",
    ops: ["RULESET_LIST", "RULESET_GET", "RULESET_CREATE", "RULESET_UPDATE", "RULESET_DELETE", "RULESET_LIST_RULE_EVALUATIONS", "RULESET_GET_RULE_SUITE", "RULESET_LIST_ORG_RULESETS"],
  },
  {
    label: "🌍 Environments",
    ops: ["ENVIRONMENT_LIST", "ENVIRONMENT_GET", "ENVIRONMENT_CREATE", "ENVIRONMENT_UPDATE", "ENVIRONMENT_DELETE", "ENVIRONMENT_LIST_SECRETS", "ENVIRONMENT_GET_SECRET", "ENVIRONMENT_CREATE_SECRET", "ENVIRONMENT_DELETE_SECRET", "ENVIRONMENT_LIST_PROTECTION_RULES"],
  },
  {
    label: "🔐 Secrets",
    ops: ["SECRET_LIST_REPO", "SECRET_GET_REPO", "SECRET_CREATE_REPO", "SECRET_DELETE_REPO", "SECRET_LIST_ORG", "SECRET_GET_ORG", "SECRET_CREATE_ORG", "SECRET_DELETE_ORG", "SECRET_GET_PUBLIC_KEY", "SECRET_GET_ORG_PUBLIC_KEY", "SECRET_LIST_SELECTED_REPOS", "SECRET_SET_SELECTED_REPOS"],
  },
  {
    label: "🚀 Deployments",
    ops: ["DEPLOYMENT_LIST", "DEPLOYMENT_GET", "DEPLOYMENT_CREATE", "DEPLOYMENT_LIST_STATUSES", "DEPLOYMENT_GET_STATUS", "DEPLOYMENT_CREATE_STATUS", "DEPLOYMENT_DELETE", "DEPLOYMENT_SET_STATUS"],
  },
  {
    label: "📦 Packages",
    ops: ["PACKAGE_LIST_FOR_USER", "PACKAGE_LIST_FOR_ORG", "PACKAGE_GET", "PACKAGE_DELETE", "PACKAGE_RESTORE", "PACKAGE_LIST_VERSIONS", "PACKAGE_GET_VERSION", "PACKAGE_DELETE_VERSION", "PACKAGE_RESTORE_VERSION", "PACKAGE_LIST_DOCKER_IMAGES"],
  },
  {
    label: "🛡️ Attestations",
    ops: ["ATTESTATION_LIST_FOR_REPO", "ATTESTATION_GET", "ATTESTATION_CREATE", "ATTESTATION_LIST_FOR_ORG", "ATTESTATION_VERIFY"],
  },
  {
    label: "🤖 Agent Tasks",
    ops: ["AGENT_TASK_LIST", "AGENT_TASK_GET", "AGENT_TASK_CREATE", "AGENT_TASK_UPDATE", "AGENT_TASK_CANCEL", "AGENT_TASK_GET_LOGS"],
  },
  {
    label: "📎 Artifacts",
    ops: ["ARTIFACT_LIST", "ARTIFACT_GET", "ARTIFACT_DELETE", "ARTIFACT_DOWNLOAD", "ARTIFACT_UPLOAD", "ARTIFACT_GET_ARCHIVE_URL"],
  },
  {
    label: "📋 Projects V2",
    ops: ["PROJECT_V2_LIST", "PROJECT_V2_GET", "PROJECT_V2_CREATE", "PROJECT_V2_UPDATE", "PROJECT_V2_DELETE", "PROJECT_V2_LIST_ITEMS", "PROJECT_V2_ADD_ITEM", "PROJECT_V2_UPDATE_ITEM", "PROJECT_V2_DELETE_ITEM", "PROJECT_V2_LIST_FIELDS", "PROJECT_V2_CREATE_FIELD", "PROJECT_V2_UPDATE_FIELD_VALUE"],
  },
  {
    label: "🔒 Security Advisories",
    ops: ["ADVISORY_LIST", "ADVISORY_GET", "ADVISORY_CREATE", "ADVISORY_UPDATE", "ADVISORY_LIST_REPOS_AFFECTED", "ADVISORY_REPORT"],
  },
]

/** Determine which field group a given operation belongs to */
export function getFieldCategory(op: string): string {
  if (op.startsWith("REPOSITORY_") || op.startsWith("FILE_") || op.startsWith("BRANCH_") || op.startsWith("RELEASE_") || op.startsWith("GIST_")) return "repo"
  if (op.startsWith("ISSUE_") || op.startsWith("PULL_REQUEST_") || op.startsWith("DISCUSSION_")) return "issues"
  if (op.startsWith("WORKFLOW_") || op.startsWith("DEPLOYMENT_") || op.startsWith("AGENT_TASK_") || op.startsWith("ARTIFACT_")) return "workflows"
  if (op.startsWith("USER_") || op.startsWith("ORG_") || op.startsWith("SECRET_") || op.startsWith("ENVIRONMENT_") || op.startsWith("PACKAGE_")) return "users-orgs"
  if (op.startsWith("SEARCH_") || op.startsWith("CODESPACES_") || op.startsWith("COPILOT_") || op.startsWith("RULESET_") || op.startsWith("PROJECT_V2_") || op.startsWith("ATTESTATION_") || op.startsWith("ADVISORY_")) return "search-misc"
  return "generic"
}
