// ─────────────────────────────────────────────────────────────
// Nodebase — Shared Execution Enums
// ─────────────────────────────────────────────────────────────

export enum IfElseOperator {
  EQUALS = "EQUALS",
  NOT_EQUALS = "NOT_EQUALS",
  CONTAINS = "CONTAINS",
  NOT_CONTAINS = "NOT_CONTAINS",
  STARTS_WITH = "STARTS_WITH",
  ENDS_WITH = "ENDS_WITH",
  GREATER_THAN = "GREATER_THAN",
  LESS_THAN = "LESS_THAN",
  GREATER_THAN_OR_EQUAL = "GREATER_THAN_OR_EQUAL",
  LESS_THAN_OR_EQUAL = "LESS_THAN_OR_EQUAL",
  IS_EMPTY = "IS_EMPTY",
  IS_NOT_EMPTY = "IS_NOT_EMPTY",
  IS_TRUE = "IS_TRUE",
  IS_FALSE = "IS_FALSE",
  REGEX_MATCH = "REGEX_MATCH",
}

export enum GmailOperation {
  SEND = "SEND",
  REPLY = "REPLY",
  FORWARD = "FORWARD",
  GET_MESSAGE = "GET_MESSAGE",
  LIST_MESSAGES = "LIST_MESSAGES",
  SEARCH_MESSAGES = "SEARCH_MESSAGES",
  ADD_LABEL = "ADD_LABEL",
  REMOVE_LABEL = "REMOVE_LABEL",
  MARK_READ = "MARK_READ",
  MARK_UNREAD = "MARK_UNREAD",
  MOVE_TO_TRASH = "MOVE_TO_TRASH",
  CREATE_DRAFT = "CREATE_DRAFT",
  GET_ATTACHMENT = "GET_ATTACHMENT",
  GET_THREAD = "GET_THREAD",
  LIST_LABELS = "LIST_LABELS",
  CREATE_LABEL = "CREATE_LABEL",
  LIST_DRAFTS = "LIST_DRAFTS",
  SEND_DRAFT = "SEND_DRAFT",
}

export enum GoogleSheetsOp {
  APPEND_ROW = "APPEND_ROW",
  READ_ROWS = "READ_ROWS",
  UPDATE_ROW = "UPDATE_ROW",
  UPDATE_ROWS_BY_QUERY = "UPDATE_ROWS_BY_QUERY",
  DELETE_ROW = "DELETE_ROW",
  GET_ROW_BY_NUMBER = "GET_ROW_BY_NUMBER",
  SEARCH_ROWS = "SEARCH_ROWS",
  CLEAR_RANGE = "CLEAR_RANGE",
  CREATE_SHEET = "CREATE_SHEET",
  GET_SHEET_INFO = "GET_SHEET_INFO",
}

export enum GoogleDriveOperation {
  UPLOAD_FILE = "UPLOAD_FILE",
  DOWNLOAD_FILE = "DOWNLOAD_FILE",
  LIST_FILES = "LIST_FILES",
  CREATE_FOLDER = "CREATE_FOLDER",
}

export enum WhatsAppOperation {
  SEND_TEXT = "SEND_TEXT",
  SEND_TEMPLATE = "SEND_TEMPLATE",
  SEND_IMAGE = "SEND_IMAGE",
  SEND_DOCUMENT = "SEND_DOCUMENT",
  SEND_REACTION = "SEND_REACTION",
}

export enum NotionOperation {
  QUERY_DATABASE = "QUERY_DATABASE",
  CREATE_DATABASE_PAGE = "CREATE_DATABASE_PAGE",
  UPDATE_DATABASE_PAGE = "UPDATE_DATABASE_PAGE",
  GET_PAGE = "GET_PAGE",
  ARCHIVE_PAGE = "ARCHIVE_PAGE",
  APPEND_BLOCK = "APPEND_BLOCK",
  GET_BLOCK_CHILDREN = "GET_BLOCK_CHILDREN",
  SEARCH = "SEARCH",
  GET_DATABASE = "GET_DATABASE",
  GET_USER = "GET_USER",
  GET_USERS = "GET_USERS",
}

export enum RazorpayOperation {
  ORDER_CREATE = "ORDER_CREATE",
  ORDER_FETCH = "ORDER_FETCH",
  ORDER_FETCH_PAYMENTS = "ORDER_FETCH_PAYMENTS",
  ORDER_LIST = "ORDER_LIST",
  PAYMENT_FETCH = "PAYMENT_FETCH",
  PAYMENT_CAPTURE = "PAYMENT_CAPTURE",
  PAYMENT_LIST = "PAYMENT_LIST",
  PAYMENT_UPDATE = "PAYMENT_UPDATE",
  REFUND_CREATE = "REFUND_CREATE",
  REFUND_FETCH = "REFUND_FETCH",
  REFUND_LIST = "REFUND_LIST",
  CUSTOMER_CREATE = "CUSTOMER_CREATE",
  CUSTOMER_FETCH = "CUSTOMER_FETCH",
  CUSTOMER_UPDATE = "CUSTOMER_UPDATE",
  SUBSCRIPTION_CREATE = "SUBSCRIPTION_CREATE",
  SUBSCRIPTION_FETCH = "SUBSCRIPTION_FETCH",
  SUBSCRIPTION_CANCEL = "SUBSCRIPTION_CANCEL",
  INVOICE_CREATE = "INVOICE_CREATE",
  INVOICE_FETCH = "INVOICE_FETCH",
  INVOICE_SEND = "INVOICE_SEND",
  INVOICE_CANCEL = "INVOICE_CANCEL",
  PAYMENT_LINK_CREATE = "PAYMENT_LINK_CREATE",
  PAYMENT_LINK_FETCH = "PAYMENT_LINK_FETCH",
  PAYMENT_LINK_UPDATE = "PAYMENT_LINK_UPDATE",
  PAYMENT_LINK_CANCEL = "PAYMENT_LINK_CANCEL",
  PAYOUT_CREATE = "PAYOUT_CREATE",
  PAYOUT_FETCH = "PAYOUT_FETCH",
  VERIFY_PAYMENT_SIGNATURE = "VERIFY_PAYMENT_SIGNATURE",
}

export enum SlackOperation {
  MESSAGE_SEND_WEBHOOK = "MESSAGE_SEND_WEBHOOK",
  MESSAGE_SEND = "MESSAGE_SEND",
  MESSAGE_UPDATE = "MESSAGE_UPDATE",
  MESSAGE_DELETE = "MESSAGE_DELETE",
  MESSAGE_GET_PERMALINK = "MESSAGE_GET_PERMALINK",
  MESSAGE_SCHEDULE = "MESSAGE_SCHEDULE",
  // legacy — kept for backward compat
  MESSAGE_SEARCH = "MESSAGE_SEARCH",
  CHANNEL_GET = "CHANNEL_GET",
  CHANNEL_LIST = "CHANNEL_LIST",
  CHANNEL_CREATE = "CHANNEL_CREATE",
  CHANNEL_ARCHIVE = "CHANNEL_ARCHIVE",
  CHANNEL_UNARCHIVE = "CHANNEL_UNARCHIVE",
  CHANNEL_INVITE = "CHANNEL_INVITE",
  CHANNEL_KICK = "CHANNEL_KICK",
  CHANNEL_SET_TOPIC = "CHANNEL_SET_TOPIC",
  CHANNEL_SET_PURPOSE = "CHANNEL_SET_PURPOSE",
  // legacy — kept for backward compat
  CHANNEL_HISTORY = "CHANNEL_HISTORY",
  CHANNEL_INFO = "CHANNEL_INFO",
  CHANNEL_RENAME = "CHANNEL_RENAME",
  USER_GET = "USER_GET",
  USER_GET_BY_EMAIL = "USER_GET_BY_EMAIL",
  USER_LIST = "USER_LIST",
  USER_SET_STATUS = "USER_SET_STATUS",
  // legacy — kept for backward compat
  USER_INFO = "USER_INFO",
  USER_GET_PRESENCE = "USER_GET_PRESENCE",
  REACTION_ADD = "REACTION_ADD",
  REACTION_REMOVE = "REACTION_REMOVE",
  REACTION_GET = "REACTION_GET",
  FILE_UPLOAD = "FILE_UPLOAD",
  FILE_GET = "FILE_GET",
  FILE_DELETE = "FILE_DELETE",
  // legacy — kept for backward compat
  FILE_LIST = "FILE_LIST",
  FILE_INFO = "FILE_INFO",
  CONVERSATION_OPEN = "CONVERSATION_OPEN",
}

export enum Msg91Operation {
  SEND_SMS = "SEND_SMS",
  SEND_BULK_SMS = "SEND_BULK_SMS",
  SEND_TRANSACTIONAL = "SEND_TRANSACTIONAL",
  SCHEDULE_SMS = "SCHEDULE_SMS",
  SEND_OTP = "SEND_OTP",
  VERIFY_OTP = "VERIFY_OTP",
  RESEND_OTP = "RESEND_OTP",
  INVALIDATE_OTP = "INVALIDATE_OTP",
  SEND_WHATSAPP = "SEND_WHATSAPP",
  SEND_WHATSAPP_MEDIA = "SEND_WHATSAPP_MEDIA",
  SEND_VOICE_OTP = "SEND_VOICE_OTP",
  SEND_EMAIL = "SEND_EMAIL",
  GET_BALANCE = "GET_BALANCE",
  GET_REPORT = "GET_REPORT",
}

export enum ShiprocketOperation {
  CREATE_ORDER = "CREATE_ORDER",
  GET_ORDER = "GET_ORDER",
  CANCEL_ORDER = "CANCEL_ORDER",
  UPDATE_ORDER = "UPDATE_ORDER",
  GET_ORDER_TRACKING = "GET_ORDER_TRACKING",
  CLONE_ORDER = "CLONE_ORDER",
  GENERATE_AWB = "GENERATE_AWB",
  GET_ORDERS_LIST = "GET_ORDERS_LIST",
  TRACK_SHIPMENT = "TRACK_SHIPMENT",
  ASSIGN_COURIER = "ASSIGN_COURIER",
  GENERATE_LABEL = "GENERATE_LABEL",
  GENERATE_MANIFEST = "GENERATE_MANIFEST",
  REQUEST_PICKUP = "REQUEST_PICKUP",
  GET_COURIER_LIST = "GET_COURIER_LIST",
  GET_RATE = "GET_RATE",
  CHECK_SERVICEABILITY = "CHECK_SERVICEABILITY",
  CREATE_RETURN = "CREATE_RETURN",
  GET_RETURN_REASONS = "GET_RETURN_REASONS",
  TRACK_RETURN = "TRACK_RETURN",
  CREATE_PRODUCT = "CREATE_PRODUCT",
  GET_PRODUCTS = "GET_PRODUCTS",
  GET_PICKUP_LOCATIONS = "GET_PICKUP_LOCATIONS",
  CREATE_PICKUP_LOCATION = "CREATE_PICKUP_LOCATION",
}

export enum ZohoCrmOperation {
  CREATE_LEAD = "CREATE_LEAD",
  GET_LEAD = "GET_LEAD",
  UPDATE_LEAD = "UPDATE_LEAD",
  DELETE_LEAD = "DELETE_LEAD",
  SEARCH_LEADS = "SEARCH_LEADS",
  CONVERT_LEAD = "CONVERT_LEAD",
  
  CREATE_CONTACT = "CREATE_CONTACT",
  GET_CONTACT = "GET_CONTACT",
  UPDATE_CONTACT = "UPDATE_CONTACT",
  DELETE_CONTACT = "DELETE_CONTACT",
  SEARCH_CONTACTS = "SEARCH_CONTACTS",
  GET_CONTACT_DEALS = "GET_CONTACT_DEALS",
  
  CREATE_DEAL = "CREATE_DEAL",
  GET_DEAL = "GET_DEAL",
  UPDATE_DEAL = "UPDATE_DEAL",
  DELETE_DEAL = "DELETE_DEAL",
  SEARCH_DEALS = "SEARCH_DEALS",
  UPDATE_DEAL_STAGE = "UPDATE_DEAL_STAGE",
  
  CREATE_ACCOUNT = "CREATE_ACCOUNT",
  GET_ACCOUNT = "GET_ACCOUNT",
  UPDATE_ACCOUNT = "UPDATE_ACCOUNT",
  DELETE_ACCOUNT = "DELETE_ACCOUNT",
  SEARCH_ACCOUNTS = "SEARCH_ACCOUNTS",
  
  CREATE_TASK = "CREATE_TASK",
  CREATE_CALL_LOG = "CREATE_CALL_LOG",
  CREATE_MEETING = "CREATE_MEETING",
  GET_ACTIVITIES = "GET_ACTIVITIES",
  
  ADD_NOTE = "ADD_NOTE",
  GET_NOTES = "GET_NOTES",
  
  UPSERT_RECORD = "UPSERT_RECORD",
  SEARCH_RECORDS = "SEARCH_RECORDS",
  GET_FIELDS = "GET_FIELDS",
}

export enum HubspotOperation {
  // ── CONTACTS ──────────────────────────────────────────────
  CREATE_CONTACT = "CREATE_CONTACT",
  GET_CONTACT = "GET_CONTACT",
  UPDATE_CONTACT = "UPDATE_CONTACT",
  DELETE_CONTACT = "DELETE_CONTACT",
  SEARCH_CONTACTS = "SEARCH_CONTACTS",
  GET_CONTACT_PROPERTIES = "GET_CONTACT_PROPERTIES",
  UPSERT_CONTACT = "UPSERT_CONTACT",
  GET_CONTACT_ASSOCIATIONS = "GET_CONTACT_ASSOCIATIONS",
  
  // ── COMPANIES ─────────────────────────────────────────────
  CREATE_COMPANY = "CREATE_COMPANY",
  GET_COMPANY = "GET_COMPANY",
  UPDATE_COMPANY = "UPDATE_COMPANY",
  DELETE_COMPANY = "DELETE_COMPANY",
  SEARCH_COMPANIES = "SEARCH_COMPANIES",
  
  // ── DEALS ─────────────────────────────────────────────────
  CREATE_DEAL = "CREATE_DEAL",
  GET_DEAL = "GET_DEAL",
  UPDATE_DEAL = "UPDATE_DEAL",
  DELETE_DEAL = "DELETE_DEAL",
  SEARCH_DEALS = "SEARCH_DEALS",
  UPDATE_DEAL_STAGE = "UPDATE_DEAL_STAGE",
  
  // ── TICKETS ───────────────────────────────────────────────
  CREATE_TICKET = "CREATE_TICKET",
  GET_TICKET = "GET_TICKET",
  UPDATE_TICKET = "UPDATE_TICKET",
  DELETE_TICKET = "DELETE_TICKET",
  SEARCH_TICKETS = "SEARCH_TICKETS",
  
  // ── ACTIVITIES ────────────────────────────────────────────
  CREATE_NOTE = "CREATE_NOTE",
  CREATE_TASK = "CREATE_TASK",
  CREATE_CALL = "CREATE_CALL",
  CREATE_EMAIL_LOG = "CREATE_EMAIL_LOG",
  
  // ── ASSOCIATIONS ──────────────────────────────────────────
  CREATE_ASSOCIATION = "CREATE_ASSOCIATION",
  DELETE_ASSOCIATION = "DELETE_ASSOCIATION",
  
  // ── LISTS ─────────────────────────────────────────────────
  ADD_CONTACT_TO_LIST = "ADD_CONTACT_TO_LIST",
  REMOVE_CONTACT_FROM_LIST = "REMOVE_CONTACT_FROM_LIST",
  GET_LIST_CONTACTS = "GET_LIST_CONTACTS",
  
  // ── GENERIC ───────────────────────────────────────────────
  SEARCH_OBJECTS = "SEARCH_OBJECTS",
  GET_PROPERTIES = "GET_PROPERTIES",
}

export enum FreshdeskOperation {
  // ── TICKETS ──────────────────────────────────────────────
  CREATE_TICKET = "CREATE_TICKET",
  GET_TICKET = "GET_TICKET",
  UPDATE_TICKET = "UPDATE_TICKET",
  DELETE_TICKET = "DELETE_TICKET",
  LIST_TICKETS = "LIST_TICKETS",
  SEARCH_TICKETS = "SEARCH_TICKETS",
  GET_TICKET_FIELDS = "GET_TICKET_FIELDS",
  RESTORE_TICKET = "RESTORE_TICKET",
  
  // ── TICKET NOTES ─────────────────────────────────────────
  ADD_NOTE = "ADD_NOTE",
  LIST_NOTES = "LIST_NOTES",
  UPDATE_NOTE = "UPDATE_NOTE",
  DELETE_NOTE = "DELETE_NOTE",
  
  // ── CONTACTS ─────────────────────────────────────────────
  CREATE_CONTACT = "CREATE_CONTACT",
  GET_CONTACT = "GET_CONTACT",
  UPDATE_CONTACT = "UPDATE_CONTACT",
  DELETE_CONTACT = "DELETE_CONTACT",
  LIST_CONTACTS = "LIST_CONTACTS",
  SEARCH_CONTACTS = "SEARCH_CONTACTS",
  MERGE_CONTACT = "MERGE_CONTACT",
  
  // ── COMPANIES ────────────────────────────────────────────
  CREATE_COMPANY = "CREATE_COMPANY",
  GET_COMPANY = "GET_COMPANY",
  UPDATE_COMPANY = "UPDATE_COMPANY",
  DELETE_COMPANY = "DELETE_COMPANY",
  LIST_COMPANIES = "LIST_COMPANIES",
  
  // ── AGENTS ───────────────────────────────────────────────
  LIST_AGENTS = "LIST_AGENTS",
  GET_AGENT = "GET_AGENT",
  UPDATE_AGENT = "UPDATE_AGENT",
  
  // ── CONVERSATIONS ────────────────────────────────────────
  LIST_CONVERSATIONS = "LIST_CONVERSATIONS",
  SEND_REPLY = "SEND_REPLY",
  CREATE_OUTBOUND_EMAIL = "CREATE_OUTBOUND_EMAIL",
  
  // ── GENERIC ──────────────────────────────────────────────
  GET_TICKET_STATS = "GET_TICKET_STATS",
}

export enum MediaUploadSource {
  URL = "URL",
  BASE64 = "BASE64",
  GOOGLE_DRIVE = "GOOGLE_DRIVE",
}

export enum CashfreeOperation {
  // ── ORDERS (Payment Gateway) ──────────────────────────────
  CREATE_ORDER = "CREATE_ORDER",
  GET_ORDER = "GET_ORDER",
  TERMINATE_ORDER = "TERMINATE_ORDER",
  PAY_ORDER = "PAY_ORDER",
  
  // ── PAYMENTS ──────────────────────────────────────────────
  GET_PAYMENTS_FOR_ORDER = "GET_PAYMENTS_FOR_ORDER",
  GET_PAYMENT_BY_ID = "GET_PAYMENT_BY_ID",
  
  // ── REFUNDS ───────────────────────────────────────────────
  CREATE_REFUND = "CREATE_REFUND",
  GET_REFUND = "GET_REFUND",
  GET_ALL_REFUNDS_FOR_ORDER = "GET_ALL_REFUNDS_FOR_ORDER",
  
  // ── SETTLEMENTS ───────────────────────────────────────────
  GET_SETTLEMENTS_FOR_ORDER = "GET_SETTLEMENTS_FOR_ORDER",
  GET_ALL_SETTLEMENTS = "GET_ALL_SETTLEMENTS",
  GET_SETTLEMENT_RECON = "GET_SETTLEMENT_RECON",
  
  // ── PAYMENT LINKS ─────────────────────────────────────────
  CREATE_PAYMENT_LINK = "CREATE_PAYMENT_LINK",
  GET_PAYMENT_LINK = "GET_PAYMENT_LINK",
  CANCEL_PAYMENT_LINK = "CANCEL_PAYMENT_LINK",
  GET_ORDERS_FOR_LINK = "GET_ORDERS_FOR_LINK",
  
  // ── SUBSCRIPTIONS ─────────────────────────────────────────
  CREATE_SUBSCRIPTION_PLAN = "CREATE_SUBSCRIPTION_PLAN",
  GET_SUBSCRIPTION_PLAN = "GET_SUBSCRIPTION_PLAN",
  CREATE_SUBSCRIPTION = "CREATE_SUBSCRIPTION",
  GET_SUBSCRIPTION = "GET_SUBSCRIPTION",
  MANAGE_SUBSCRIPTION = "MANAGE_SUBSCRIPTION",
  GET_SUBSCRIPTION_PAYMENTS = "GET_SUBSCRIPTION_PAYMENTS",
  
  // ── PAYOUTS ───────────────────────────────────────────────
  GET_PAYOUT_BALANCE = "GET_PAYOUT_BALANCE",
  ADD_BENEFICIARY = "ADD_BENEFICIARY",
  GET_BENEFICIARY = "GET_BENEFICIARY",
  REMOVE_BENEFICIARY = "REMOVE_BENEFICIARY",
  TRANSFER_TO_BENEFICIARY = "TRANSFER_TO_BENEFICIARY",
  GET_TRANSFER_STATUS = "GET_TRANSFER_STATUS",
  BULK_TRANSFER = "BULK_TRANSFER",
  GET_BATCH_TRANSFER_STATUS = "GET_BATCH_TRANSFER_STATUS",
  
  // ── UPI ───────────────────────────────────────────────────
  VALIDATE_UPI_ID = "VALIDATE_UPI_ID",
  CREATE_UPI_PAYMENT_LINK = "CREATE_UPI_PAYMENT_LINK",
  
  // ── OFFERS ────────────────────────────────────────────────
  CREATE_OFFER = "CREATE_OFFER",
  GET_OFFER = "GET_OFFER",
  
  // ── WEBHOOKS ──────────────────────────────────────────────
  VERIFY_WEBHOOK_SIGNATURE = "VERIFY_WEBHOOK_SIGNATURE",
}

export enum GitHubOperation {
  // Repository Operations
  REPOSITORY_CREATE = "REPOSITORY_CREATE",
  REPOSITORY_GET = "REPOSITORY_GET",
  REPOSITORY_LIST = "REPOSITORY_LIST",
  REPOSITORY_UPDATE = "REPOSITORY_UPDATE",
  REPOSITORY_DELETE = "REPOSITORY_DELETE",
  REPOSITORY_FORK = "REPOSITORY_FORK",
  REPOSITORY_LIST_CONTRIBUTORS = "REPOSITORY_LIST_CONTRIBUTORS",
  REPOSITORY_LIST_LANGUAGES = "REPOSITORY_LIST_LANGUAGES",
  REPOSITORY_TRANSFER = "REPOSITORY_TRANSFER",
  REPOSITORY_DISPATCH = "REPOSITORY_DISPATCH",
  REPOSITORY_CHECK_COLLABORATOR = "REPOSITORY_CHECK_COLLABORATOR",
  REPOSITORY_LIST_EVENTS = "REPOSITORY_LIST_EVENTS",
  
  // Issue Operations
  ISSUE_CREATE = "ISSUE_CREATE",
  ISSUE_GET = "ISSUE_GET",
  ISSUE_UPDATE = "ISSUE_UPDATE",
  ISSUE_CLOSE = "ISSUE_CLOSE",
  ISSUE_REOPEN = "ISSUE_REOPEN",
  ISSUE_LIST = "ISSUE_LIST",
  ISSUE_ADD_LABELS = "ISSUE_ADD_LABELS",
  ISSUE_REMOVE_LABEL = "ISSUE_REMOVE_LABEL",
  ISSUE_CREATE_COMMENT = "ISSUE_CREATE_COMMENT",
  ISSUE_LIST_COMMENTS = "ISSUE_LIST_COMMENTS",
  ISSUE_UPDATE_COMMENT = "ISSUE_UPDATE_COMMENT",
  ISSUE_DELETE_COMMENT = "ISSUE_DELETE_COMMENT",
  ISSUE_ASSIGN = "ISSUE_ASSIGN",
  ISSUE_UNASSIGN = "ISSUE_UNASSIGN",
  
  // Pull Request Operations
  PULL_REQUEST_CREATE = "PULL_REQUEST_CREATE",
  PULL_REQUEST_GET = "PULL_REQUEST_GET",
  PULL_REQUEST_LIST = "PULL_REQUEST_LIST",
  PULL_REQUEST_UPDATE = "PULL_REQUEST_UPDATE",
  PULL_REQUEST_MERGE = "PULL_REQUEST_MERGE",
  PULL_REQUEST_CLOSE = "PULL_REQUEST_CLOSE",
  PULL_REQUEST_REOPEN = "PULL_REQUEST_REOPEN",
  PULL_REQUEST_LIST_REVIEWS = "PULL_REQUEST_LIST_REVIEWS",
  PULL_REQUEST_CREATE_REVIEW = "PULL_REQUEST_CREATE_REVIEW",
  PULL_REQUEST_REQUEST_REVIEWERS = "PULL_REQUEST_REQUEST_REVIEWERS",
  PULL_REQUEST_LIST_COMMITS = "PULL_REQUEST_LIST_COMMITS",
  PULL_REQUEST_LIST_FILES = "PULL_REQUEST_LIST_FILES",
  PULL_REQUEST_CREATE_REVIEW_COMMENT = "PULL_REQUEST_CREATE_REVIEW_COMMENT",
  
  // File Operations
  FILE_GET = "FILE_GET",
  FILE_CREATE = "FILE_CREATE",
  FILE_UPDATE = "FILE_UPDATE",
  FILE_DELETE = "FILE_DELETE",
  FILE_LIST = "FILE_LIST",
  FILE_GET_CONTENTS = "FILE_GET_CONTENTS",
  FILE_CREATE_OR_UPDATE = "FILE_CREATE_OR_UPDATE",
  
  // Branch Operations
  BRANCH_LIST = "BRANCH_LIST",
  BRANCH_GET = "BRANCH_GET",
  BRANCH_CREATE = "BRANCH_CREATE",
  BRANCH_DELETE = "BRANCH_DELETE",
  BRANCH_RENAME = "BRANCH_RENAME",
  BRANCH_SET_PROTECTION = "BRANCH_SET_PROTECTION",
  
  // Release Operations
  RELEASE_CREATE = "RELEASE_CREATE",
  RELEASE_GET = "RELEASE_GET",
  RELEASE_LIST = "RELEASE_LIST",
  RELEASE_UPDATE = "RELEASE_UPDATE",
  RELEASE_DELETE = "RELEASE_DELETE",
  RELEASE_UPLOAD_ASSET = "RELEASE_UPLOAD_ASSET",
  
  // Workflow Operations
  WORKFLOW_LIST = "WORKFLOW_LIST",
  WORKFLOW_GET = "WORKFLOW_GET",
  WORKFLOW_DISPATCH = "WORKFLOW_DISPATCH",
  WORKFLOW_RUN_LIST = "WORKFLOW_RUN_LIST",
  WORKFLOW_RUN_GET = "WORKFLOW_RUN_GET",
  WORKFLOW_RUN_CANCEL = "WORKFLOW_RUN_CANCEL",
  WORKFLOW_RUN_RE_RUN = "WORKFLOW_RUN_RE_RUN",
  WORKFLOW_RUN_LIST_JOBS = "WORKFLOW_RUN_LIST_JOBS",
  
  // Gist Operations
  GIST_CREATE = "GIST_CREATE",
  GIST_GET = "GIST_GET",
  GIST_LIST = "GIST_LIST",
  GIST_UPDATE = "GIST_UPDATE",
  GIST_DELETE = "GIST_DELETE",
  GIST_STAR = "GIST_STAR",
  
  // Search Operations
  SEARCH_REPOSITORIES = "SEARCH_REPOSITORIES",
  SEARCH_ISSUES = "SEARCH_ISSUES",
  SEARCH_PULL_REQUESTS = "SEARCH_PULL_REQUESTS",
  SEARCH_CODE = "SEARCH_CODE",
  SEARCH_USERS = "SEARCH_USERS",
  SEARCH_COMMITS = "SEARCH_COMMITS",
  SEARCH_TOPICS = "SEARCH_TOPICS",
  
  // User Operations
  USER_GET = "USER_GET",
  USER_GET_CURRENT = "USER_GET_CURRENT",
  USER_LIST_REPOS = "USER_LIST_REPOS",
  USER_LIST_FOLLOWERS = "USER_LIST_FOLLOWERS",
  USER_LIST_FOLLOWING = "USER_LIST_FOLLOWING",
  
  // Organization Operations
  ORG_GET = "ORG_GET",
  ORG_LIST = "ORG_LIST",
  ORG_LIST_MEMBERS = "ORG_LIST_MEMBERS",
  ORG_LIST_TEAMS = "ORG_LIST_TEAMS",
  ORG_LIST_REPOS = "ORG_LIST_REPOS",
  ORG_CREATE_REPO = "ORG_CREATE_REPO",
  ORG_INVITE_MEMBER = "ORG_INVITE_MEMBER",
  ORG_REMOVE_MEMBER = "ORG_REMOVE_MEMBER",
  
  // Discussion Operations
  DISCUSSION_CREATE = "DISCUSSION_CREATE",
  DISCUSSION_GET = "DISCUSSION_GET",
  DISCUSSION_LIST = "DISCUSSION_LIST",
  DISCUSSION_UPDATE = "DISCUSSION_UPDATE",
  DISCUSSION_DELETE = "DISCUSSION_DELETE",
  
  // Codespaces (NEW)
  CODESPACES_LIST = "CODESPACES_LIST",
  CODESPACES_GET = "CODESPACES_GET",
  CODESPACES_CREATE = "CODESPACES_CREATE",
  CODESPACES_START = "CODESPACES_START",
  CODESPACES_STOP = "CODESPACES_STOP",
  CODESPACES_DELETE = "CODESPACES_DELETE",
  CODESPACES_UPDATE = "CODESPACES_UPDATE",
  CODESPACES_EXPORT = "CODESPACES_EXPORT",
  CODESPACES_LIST_FOR_REPO = "CODESPACES_LIST_FOR_REPO",
  CODESPACES_LIST_MACHINE_TYPES = "CODESPACES_LIST_MACHINE_TYPES",
  CODESPACES_LIST_SECRETS = "CODESPACES_LIST_SECRETS",
  CODESPACES_CREATE_SECRET = "CODESPACES_CREATE_SECRET",
  
  // Copilot (NEW)
  COPILOT_LIST_SEATS = "COPILOT_LIST_SEATS",
  COPILOT_ADD_SEAT = "COPILOT_ADD_SEAT",
  COPILOT_REMOVE_SEAT = "COPILOT_REMOVE_SEAT",
  COPILOT_GET_SETTINGS = "COPILOT_GET_SETTINGS",
  COPILOT_UPDATE_SETTINGS = "COPILOT_UPDATE_SETTINGS",
  COPILOT_LIST_SPACES = "COPILOT_LIST_SPACES",
  COPILOT_GET_SPACE = "COPILOT_GET_SPACE",
  COPILOT_CREATE_SPACE = "COPILOT_CREATE_SPACE",
  COPILOT_UPDATE_SPACE = "COPILOT_UPDATE_SPACE",
  COPILOT_DELETE_SPACE = "COPILOT_DELETE_SPACE",
  COPILOT_LIST_SPACE_RESOURCES = "COPILOT_LIST_SPACE_RESOURCES",
  COPILOT_ADD_SPACE_RESOURCE = "COPILOT_ADD_SPACE_RESOURCE",
  COPILOT_REMOVE_SPACE_RESOURCE = "COPILOT_REMOVE_SPACE_RESOURCE",
  COPILOT_GET_AGENT_POLICY = "COPILOT_GET_AGENT_POLICY",
  COPILOT_UPDATE_AGENT_POLICY = "COPILOT_UPDATE_AGENT_POLICY",
  
  // Rulesets (NEW)
  RULESET_LIST = "RULESET_LIST",
  RULESET_GET = "RULESET_GET",
  RULESET_CREATE = "RULESET_CREATE",
  RULESET_UPDATE = "RULESET_UPDATE",
  RULESET_DELETE = "RULESET_DELETE",
  RULESET_LIST_RULE_EVALUATIONS = "RULESET_LIST_RULE_EVALUATIONS",
  RULESET_GET_RULE_SUITE = "RULESET_GET_RULE_SUITE",
  RULESET_LIST_ORG_RULESETS = "RULESET_LIST_ORG_RULESETS",
  
  // Environments (NEW)
  ENVIRONMENT_LIST = "ENVIRONMENT_LIST",
  ENVIRONMENT_GET = "ENVIRONMENT_GET",
  ENVIRONMENT_CREATE = "ENVIRONMENT_CREATE",
  ENVIRONMENT_UPDATE = "ENVIRONMENT_UPDATE",
  ENVIRONMENT_DELETE = "ENVIRONMENT_DELETE",
  ENVIRONMENT_LIST_SECRETS = "ENVIRONMENT_LIST_SECRETS",
  ENVIRONMENT_GET_SECRET = "ENVIRONMENT_GET_SECRET",
  ENVIRONMENT_CREATE_SECRET = "ENVIRONMENT_CREATE_SECRET",
  ENVIRONMENT_DELETE_SECRET = "ENVIRONMENT_DELETE_SECRET",
  ENVIRONMENT_LIST_PROTECTION_RULES = "ENVIRONMENT_LIST_PROTECTION_RULES",
  
  // Secrets (NEW)
  SECRET_LIST_REPO = "SECRET_LIST_REPO",
  SECRET_GET_REPO = "SECRET_GET_REPO",
  SECRET_CREATE_REPO = "SECRET_CREATE_REPO",
  SECRET_DELETE_REPO = "SECRET_DELETE_REPO",
  SECRET_LIST_ORG = "SECRET_LIST_ORG",
  SECRET_GET_ORG = "SECRET_GET_ORG",
  SECRET_CREATE_ORG = "SECRET_CREATE_ORG",
  SECRET_DELETE_ORG = "SECRET_DELETE_ORG",
  SECRET_GET_PUBLIC_KEY = "SECRET_GET_PUBLIC_KEY",
  SECRET_GET_ORG_PUBLIC_KEY = "SECRET_GET_ORG_PUBLIC_KEY",
  SECRET_LIST_SELECTED_REPOS = "SECRET_LIST_SELECTED_REPOS",
  SECRET_SET_SELECTED_REPOS = "SECRET_SET_SELECTED_REPOS",
  
  // Deployments (NEW)
  DEPLOYMENT_LIST = "DEPLOYMENT_LIST",
  DEPLOYMENT_GET = "DEPLOYMENT_GET",
  DEPLOYMENT_CREATE = "DEPLOYMENT_CREATE",
  DEPLOYMENT_LIST_STATUSES = "DEPLOYMENT_LIST_STATUSES",
  DEPLOYMENT_GET_STATUS = "DEPLOYMENT_GET_STATUS",
  DEPLOYMENT_CREATE_STATUS = "DEPLOYMENT_CREATE_STATUS",
  DEPLOYMENT_DELETE = "DEPLOYMENT_DELETE",
  DEPLOYMENT_SET_STATUS = "DEPLOYMENT_SET_STATUS",
  
  // Packages (NEW)
  PACKAGE_LIST_FOR_USER = "PACKAGE_LIST_FOR_USER",
  PACKAGE_LIST_FOR_ORG = "PACKAGE_LIST_FOR_ORG",
  PACKAGE_GET = "PACKAGE_GET",
  PACKAGE_DELETE = "PACKAGE_DELETE",
  PACKAGE_RESTORE = "PACKAGE_RESTORE",
  PACKAGE_LIST_VERSIONS = "PACKAGE_LIST_VERSIONS",
  PACKAGE_GET_VERSION = "PACKAGE_GET_VERSION",
  PACKAGE_DELETE_VERSION = "PACKAGE_DELETE_VERSION",
  PACKAGE_RESTORE_VERSION = "PACKAGE_RESTORE_VERSION",
  PACKAGE_LIST_DOCKER_IMAGES = "PACKAGE_LIST_DOCKER_IMAGES",
  
  // Attestations (NEW)
  ATTESTATION_LIST_FOR_REPO = "ATTESTATION_LIST_FOR_REPO",
  ATTESTATION_GET = "ATTESTATION_GET",
  ATTESTATION_CREATE = "ATTESTATION_CREATE",
  ATTESTATION_LIST_FOR_ORG = "ATTESTATION_LIST_FOR_ORG",
  ATTESTATION_VERIFY = "ATTESTATION_VERIFY",
  
  // Agent Tasks (NEW)
  AGENT_TASK_LIST = "AGENT_TASK_LIST",
  AGENT_TASK_GET = "AGENT_TASK_GET",
  AGENT_TASK_CREATE = "AGENT_TASK_CREATE",
  AGENT_TASK_UPDATE = "AGENT_TASK_UPDATE",
  AGENT_TASK_CANCEL = "AGENT_TASK_CANCEL",
  AGENT_TASK_GET_LOGS = "AGENT_TASK_GET_LOGS",
  
  // Artifacts (NEW)
  ARTIFACT_LIST = "ARTIFACT_LIST",
  ARTIFACT_GET = "ARTIFACT_GET",
  ARTIFACT_DELETE = "ARTIFACT_DELETE",
  ARTIFACT_DOWNLOAD = "ARTIFACT_DOWNLOAD",
  ARTIFACT_UPLOAD = "ARTIFACT_UPLOAD",
  ARTIFACT_GET_ARCHIVE_URL = "ARTIFACT_GET_ARCHIVE_URL",
  
  // Projects V2 (NEW)
  PROJECT_V2_LIST = "PROJECT_V2_LIST",
  PROJECT_V2_GET = "PROJECT_V2_GET",
  PROJECT_V2_CREATE = "PROJECT_V2_CREATE",
  PROJECT_V2_UPDATE = "PROJECT_V2_UPDATE",
  PROJECT_V2_DELETE = "PROJECT_V2_DELETE",
  PROJECT_V2_LIST_ITEMS = "PROJECT_V2_LIST_ITEMS",
  PROJECT_V2_ADD_ITEM = "PROJECT_V2_ADD_ITEM",
  PROJECT_V2_UPDATE_ITEM = "PROJECT_V2_UPDATE_ITEM",
  PROJECT_V2_DELETE_ITEM = "PROJECT_V2_DELETE_ITEM",
  PROJECT_V2_LIST_FIELDS = "PROJECT_V2_LIST_FIELDS",
  PROJECT_V2_CREATE_FIELD = "PROJECT_V2_CREATE_FIELD",
  PROJECT_V2_UPDATE_FIELD_VALUE = "PROJECT_V2_UPDATE_FIELD_VALUE",
  
  // Security Advisories (NEW)
  ADVISORY_LIST = "ADVISORY_LIST",
  ADVISORY_GET = "ADVISORY_GET",
  ADVISORY_CREATE = "ADVISORY_CREATE",
  ADVISORY_UPDATE = "ADVISORY_UPDATE",
  ADVISORY_LIST_REPOS_AFFECTED = "ADVISORY_LIST_REPOS_AFFECTED",
  ADVISORY_REPORT = "ADVISORY_REPORT",
}

export enum AgentAIProvider {
  OPENAI = "OPENAI",
  CLAUDE = "CLAUDE",
  DIGITALOCEAN_GLM5 = "DIGITALOCEAN_GLM5",
}

export enum GenerationStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  REJECTED = "REJECTED",
}

export enum AgentMessageRole {
  USER = "USER",
  ASSISTANT = "ASSISTANT",
  SYSTEM = "SYSTEM",
}

export enum GuardrailViolationType {
  PROMPT_INJECTION = "PROMPT_INJECTION",
  OFF_TOPIC = "OFF_TOPIC",
  EXCESSIVE_LENGTH = "EXCESSIVE_LENGTH",
  RATE_LIMITED = "RATE_LIMITED",
  QUOTA_EXCEEDED = "QUOTA_EXCEEDED",
  HARMFUL_CONTENT = "HARMFUL_CONTENT",
  PII_DETECTED = "PII_DETECTED",
}

